spring:
  application:
    name: EmployeeProject


  datasource:
    url: jdbc:postgresql://localhost:5433/bakcell
    username: valida
    password: valida123
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 1
      maximum-pool-size: 3
      idle-timeout: 10000


  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update